AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Parameters:
  PersonName:
    Type: String

Resources:
  StatusSkill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python3.6
      Environment:
        Variables:
          PERSON_NAME: !Ref PersonName
